#!/usr/bin/env ruby

require_relative 'stats'
require_relative 'cell'
require_relative 'world'
require_relative 'game'
require_relative 'renderer/console'
require_relative 'renderer/window'

# Rules:
# - live cell with 2-3 neighbors survives
# - dead cell with 3 neighbors becomes alive
# - all other cells die or stay dead

POPULATE_RANGE=(0..1)

world = World.new
stats = Stats.new
game = Game.new(world, stats)
renderer = case ARGV.first
when /^(win|window)$/i
  Renderer::Window.new(game)
else
  Renderer::Console.new(game)
end

game.populate renderer.width, renderer.height, POPULATE_RANGE
renderer.show

puts "\n\n=== STATS ==="
stats.calculate
puts stats
puts ""